### ISSUE TITLE
Increase tile clarity/contrast.

### ISSUE THREAD

**Issue by poetaster** [poetaster/harbour-moremahjong#1]
a user, to whit: 'tile rendering lacks the clarity of the simple-mahjong-solitaire version, making it slightly harder — at least to my eyes — to distinguish the tiles'

**Comment by ffalt** [comment]
Hi, not sure if this is what the user meant and if this helps them at all: 
In [v1.4](https://github.com/ffalt/mah/releases/tag/v1.4.0) I have added a "Higher contrast" option in the settings dialog which boldens the border and the drop shadow of the tiles a little. 
<img width="228" alt="a" src="https://user-images.githubusercontent.com/3438714/161495088-f6541be5-0f6d-433b-b57f-7e6ec5d3cd5c.png">
<img width="227" alt="b" src="https://user-images.githubusercontent.com/3438714/161495093-ea260a28-676e-4ab6-8fbf-82c18f6c57ba.png">

**Comment by poetaster** [comment]
> Hi, not sure if this is what the user meant and if this helps them at all: In [v1.4](https://github.com/ffalt/mah/releases/tag/v1.4.0) I have added a "Higher contrast" option in the settings dialog which boldens the border and the drop shadow of the tiles a little. 

Yes, those are exactly the things the user, me too, were adressing. In packaging I had to manipulate the sources a bit, since it's displaying in a QT/QML WebView, so it'll take a bit of time to get to it, but it's great that you were on it!

**Comment by poetaster** [comment]
Works for me.
